### ISSUE TITLE
Firefox search bar support?

### ISSUE THREAD

**Issue by Twisted-Code** [MindustryGame/wiki-testing#4]
would it be possible to add support for the Firefox search bar so that Firefox users can more quickly search for stuff? according to a [page](https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox) I found on Firefox support, the specification for such engines [can be found here](https://developer.mozilla.org/en-US/docs/Web/OpenSearch).

**Comment by skybldev** [comment]
Transferred to wiki-testing since it will be worked on in there.

**Comment by Anuken** [comment]
Is this really something that someone here is interested in implementing? Personally, I don't have much interest in a browser-specific feature[1], and there will most likely always be something of higher priority than this on the list. It doesn't look trivial to implement, and honestly is something that the website generator should be implementing on their end.

I'll close this. Unless someone else feels like they really need this feature and are willing to submit a PR to make it happen, it won't be implemented.

*[1]: Looks like Chrome supports that spec too, but I've never seen or heard of anyone using it.*

**Comment by Twisted-Code** [comment]
okey-dokey. I was just throwing it out there, but if it's low priority, not practical, or both, totally understandable :-)
