### ISSUE TITLE
Server commands and config options

### ISSUE THREAD

**Issue by Oro** [MindustryGame/wiki-testing#5]
Both server config options (via `mindustry-server config`) and commands (`mindustry-server help`) are currently only available via commands. Would it make sense to put them into the wiki?

If yes, would you be up for a PR on either the generator (if I can hack it... my bet is unfortunately on "not with my lack of knowledge"  :) ) or hardcoded in [servers.md](docs/servers.md)?

**Comment by Anuken** [comment]
Implemented.
